### ISSUE TITLE
Experiment with TreeSitter multi-lang support and config

### ISSUE THREAD

**Issue by cmgriffing** [code-biscuits/code-biscuits.github.io#4]
See how to set up config in VSCode for multi toggling various languages

Update:

The plan is to have default config values in Settings UI similar to language specific plugins for now.

From there, we will have a languageConfig object property to configure individual languages. The encouraged way to modify this is going to be a webview.

Consider VSCode toast warnings for invalid schema.

**Comment by hansWurst-creator** [comment]
Thanks for the great work. I would absolutely love to see this for Lisp style languages.

**Comment by cmgriffing** [comment]
@hansWurst-creator  Thanks. We will be limited to available tree-sitter grammars for now. But making new custom ones could be an option eventually.

**Comment by cmgriffing** [comment]
@hansWurst-creator Go ahead and check out Assorted Biscuits.
I think we have the tree-sitter based extension ready for use now. It handles several languages, but HTML, JS/TS, and CSS/LESS/SCSS are still planned to stay separate.

https://marketplace.visualstudio.com/items?itemName=CodeBiscuits.assorted-biscuits

also on OVSX:

https://open-vsx.org/extension/CodeBiscuits/assorted-biscuits
